on: push

name: archive_nflversedata

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: create_release
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    outputs:
      releases: ${{ steps.query_releases.outputs.releases }}
    steps:
      - name: Create release with gh
        run: gh release create archive-$(date '+%Y-%m-%d') -t archive-$(date '+%Y-%m-%d') -R nflverse/nflverse-data-archives || true
      - id: query_releases
        run: echo "releases=$(gh release list -R nflverse/nflverse-data --exclude-drafts --json tagName --jq '[.[].tagName]')" > $GITHUB_OUTPUT
