on:
  - push
  - workflow_dispatch

name: archive_nflversedata

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: create_release
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    outputs:
      releases: ${{ steps.query_releases.outputs.releases }}
    steps:
      - id: query_releases
        run: echo ${{ secrets.GH_TOKEN }}
